export const STOREFRONT_CONFIG_FETCH = 'STOREFRONT_CONFIG_FETCH';
export const STOREFRONT_CONFIG_FETCH_SUCCESS = 'STOREFRONT_CONFIG_FETCH_SUCCESS';
export const STOREFRONT_CONFIG_FETCH_FAIL = 'STOREFRONT_CONFIG_FETCH_FAIL';
